remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

baseurl: "/AirWiki" # Replace with your repository name if different

url: "https://sensilab.github.io" # Note: Do not include the trailing slash
